In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head(5)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [7]:
df.rename(columns={"entity":"País"}, inplace=True) #el inplace es para indicar que sí se haga el cambio en la tabla
df.rename(columns={"code":"Código", "year":"Año", "life_expectancy_0":"Esperanza de vida"}, inplace=True)
df.head(10)

          País Código   Año  Esperanza de vida
0  Afghanistan    AFG  1950            28.1563
1  Afghanistan    AFG  1951            28.5836
2  Afghanistan    AFG  1952            29.0138
3  Afghanistan    AFG  1953            29.4521
4  Afghanistan    AFG  1954            29.6975
5  Afghanistan    AFG  1955            30.3660
6  Afghanistan    AFG  1956            30.8303
7  Afghanistan    AFG  1957            31.3451
8  Afghanistan    AFG  1958            31.8400
9  Afghanistan    AFG  1959            32.3365

In [9]:
df.set_index("País", inplace=True)