In [17]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head(5)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [18]:
df.rename(columns={"entity":"País"}, inplace=True) #el inplace es para indicar que sí se haga el cambio en la tabla
df.rename(columns={"code":"Código", "year":"Año", "life_expectancy_0":"Esperanza de vida"}, inplace=True)
df.head(10)

          País Código   Año  Esperanza de vida
0  Afghanistan    AFG  1950            28.1563
1  Afghanistan    AFG  1951            28.5836
2  Afghanistan    AFG  1952            29.0138
3  Afghanistan    AFG  1953            29.4521
4  Afghanistan    AFG  1954            29.6975
5  Afghanistan    AFG  1955            30.3660
6  Afghanistan    AFG  1956            30.8303
7  Afghanistan    AFG  1957            31.3451
8  Afghanistan    AFG  1958            31.8400
9  Afghanistan    AFG  1959            32.3365

In [22]:
#Cuando le pones index ya no lo puedes consultar, ya no es un dato es un índice. Se puede usar para localizar pero no para hacer filtros
##df.set_index("País", inplace=True)

In [19]:
df.head()

          País Código   Año  Esperanza de vida
0  Afghanistan    AFG  1950            28.1563
1  Afghanistan    AFG  1951            28.5836
2  Afghanistan    AFG  1952            29.0138
3  Afghanistan    AFG  1953            29.4521
4  Afghanistan    AFG  1954            29.6975

In [23]:
df.loc[df["País"].str.contains("UNI", case=False)]

                               País Código   Año  Esperanza de vida
15803                       Reunion    REU  1950            47.5602
15804                       Reunion    REU  1951            48.6476
15805                       Reunion    REU  1952            50.1082
15806                       Reunion    REU  1953            51.4650
15807                       Reunion    REU  1954            52.9912
...                             ...    ...   ...                ...
20581  United States Virgin Islands    VIR  2019            74.8761
20582  United States Virgin Islands    VIR  2020            74.7137
20583  United States Virgin Islands    VIR  2021            74.6132
20584  United States Virgin Islands    VIR  2022            75.0449
20585  United States Virgin Islands    VIR  2023            75.4724

[666 rows x 4 columns]

In [27]:
resultado = (
    df.groupby("País")["Esperanza de vida"]
    .mean()
    .sort_values(ascending=True)
)

In [28]:
resultado

País
USSR             32.700000
South Sudan      37.841631
Sierra Leone     43.189605
Mali             43.760793
Niger            44.187513
                   ...
Liechtenstein    76.288354
Guernsey         76.995827
Andorra          77.991046
San Marino       77.997265
Monaco           78.048231
Name: Esperanza de vida, Length: 265, dtype: float64